
[profile.default]
src = "src"
out = "artifacts"
libs = ["node_modules", "lib"]
remappings = [
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat/=node_modules/hardhat/",
]
auto_detect_solc = true
optimizer = true
optimizer_runs = 200

eth_rpc_url = "${SEPOLIA_RPC_URL}"
etherscan_api_key = "${ETHERSCAN_API_KEY}"